scan_timeout = 60
add_newline = false

[username]
style_user = "green"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
disabled = false
style = "cyan"
format = "[$hostname]($style) "

[localip]
ssh_only = false
disabled = false
style = "purple"
format = "[$localipv4]($style) "

[line_break]
disabled = false

[directory]
style = "bold blue"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "󰙧"                   # nf-md-stop_circle_outline
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = "󰏗 "                         # nf-md-package_variant_closed

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "                               # nf-fae-java

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "                           # nf-seti-go

[conda]
format = 'via [$symbol( $environment)]($style) '

[bun]
style = "bold white"

[battery]
full_symbol = "󰁹 "        # nf-md-battery
charging_symbol = "󱐋 "    # nf-md-lightning_bolt
discharging_symbol = "󰂃 " # nf-md-battery_alert
empty_symbol = "󰂎 "       # nf-md-battery_outline
